on: [push]

name: Inspections
jobs:
  runPHPCSInspection:
    name: Run PHPCS inspection
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Installing
        run: composer install
      - name: Check PHP syntax
        run: find -L .  -path ./vendor -prune -o -name '*.php' -print0 | xargs -0 -n 1 -P 4 php -l
      - name: Analyze code style
        run: ./vendor/bin/phpcs -p -s -v -n . --standard=./phpcs.xml --extensions=php
      - name: Run unit tests
        run: ./vendor/bin/phpunit
