name: PHPUnit

on: [push]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: php-actions/composer@v1
      - name: PHPUnit Tests
        run: ./vendor/bin/phpunit test
