name: PHPUnit

on: [push]

jobs:
  build-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: [7.3, 7.4] # TODO: Add 5.6 with phpunit 4.x
        wordpress: [master] # TODO: Add WP 4.9
        exclude:
          - php: 7.3
            wordpress: 4.9
          - php: 7.4
            wordpress: 4.9
    name: PHP ${{ matrix.php }} tests in WP ${{ matrix.wordpress }}
    steps:
      - uses: actions/checkout@v2

      # get the PHP version
      - uses: shivammathur/setup-php@v1
        with:
          php-version: ${{ matrix.php }}

      - uses: php-actions/composer@v1
      - name: Installing WordPress
        run: |
          export WP_DEVELOP_DIR=/tmp/wordpress/
          git clone --depth=50 --branch="${{ matrix.wordpress }}" git://develop.git.wordpress.org/ /tmp/wordpress
          cd ..
          cp -r "${GITHUB_REPOSITORY#*/}" "/tmp/wordpress/src/wp-content/plugins/${GITHUB_REPOSITORY#*/}"
          cd /tmp/wordpress/
          pwd
          cp wp-tests-config-sample.php wp-tests-config.php
          sed -i "s/youremptytestdbnamehere/wordpress_tests/" wp-tests-config.php
          sed -i "s/yourusernamehere/root/" wp-tests-config.php
          sed -i "s/yourpasswordhere/root/" wp-tests-config.php
      - name: Creating database
        run: |
          sudo /etc/init.d/mysql start
          mysql -u root -proot -e "CREATE DATABASE wordpress_tests;"
      - name: PhpUnit tests
        run: |
          cd "/tmp/wordpress/src/wp-content/plugins/${GITHUB_REPOSITORY#*/}"
          pwd
          vendor/bin/phpunit
